# Generated by Django 5.1.6 on 2025-03-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_whatsusers_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsusers',
            name='islatestmessagereaded',
            field=models.BooleanField(default=True),
        ),
    ]
