# Generated by Django 5.1.6 on 2025-03-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_whatsusers_islatestmessagereaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsusers',
            name='iscall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsusers',
            name='lastactivity',
            field=models.IntegerField(default=12),
        ),
    ]
