# Generated by Django 5.1.6 on 2025-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_whatsusers_iscall_whatsusers_lastactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsusers',
            name='calltype',
            field=models.CharField(choices=[('voice', 'voice'), ('video', 'video')], default='voice', max_length=10),
        ),
    ]
