# Generated by Django 5.1.6 on 2025-03-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_whatsusers_calltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsusers',
            name='lastcall',
            field=models.IntegerField(default=12),
        ),
    ]
